version: '3.5'

services:
  db:
    image: postgres:16
    container_name: speeches-database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: speeches
    ports:
      - "5432:5432"

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    tty: true
    restart: unless-stopped
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all

  app:
    build:
      dockerfile: ./app/Dockerfile.app
    env_file:
    - .env
    ports:
      - "8501:8501"
    depends_on:
      - ollama
    tty: true
    stdin_open: true

volumes:
  ollama_data: